### ISSUE TITLE
No CHANGELOG.md?

### ISSUE THREAD

**Issue by cabljac** [amin3mej/firebase-http-export-sheets#1]
Hi there, it's usual (and will be required for publishing) for extensions to have a CHANGELOG.md file, (see for example https://github.com/firebase/extensions/blob/next/firestore-send-email/CHANGELOG.md).

**Comment by amin3mej** [comment]
Hi @cabljac, Thanks. I just added that: https://github.com/amin3mej/firebase-http-export-sheets/commit/2caeff034f4565a36fb6901ead2e7cc90c2dcfb6
